Document: quake2
Title: Debian quake2 Manual
Author: <insert document author here>
Abstract: This manual describes what quake2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/quake2/quake2.sgml.gz

Format: postscript
Files: /usr/share/doc/quake2/quake2.ps.gz

Format: text
Files: /usr/share/doc/quake2/quake2.text.gz

Format: HTML
Index: /usr/share/doc/quake2/html/index.html
Files: /usr/share/doc/quake2/html/*.html

  
